# Generated by Django 5.1.6 on 2025-02-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0002_follows_likes_alter_chirp_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follows',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
