# Generated by Django 5.1.6 on 2025-03-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0005_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
