# Generated by Django 5.1.6 on 2025-03-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0006_chirp_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirp',
            name='public',
        ),
        migrations.AddField(
            model_name='profile',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
