# Generated by Django 5.1.6 on 2025-03-04 02:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0008_follows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follows',
            unique_together={('follower', 'followed')},
        ),
    ]
